apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: inf2.8xlarge
spec:
  template:
    spec:
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values: ["inf2"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: node.kubernetes.io/instance-type
          operator: In
          values: ["inf2.8xlarge"]
      nodeClassRef:
        name: inf2.8xlarge
  limits:
    cpu: 1000
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: 720h # 30 * 24h = 720h
---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: inf2.8xlarge
spec:
  amiFamily: AL2 # Amazon Linux 2
  role: $KarpenterNodeRole
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: $KarpenterDiscoveryTag
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: $KarpenterDiscoveryTag
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 300Gi
        volumeType: gp3
        encrypted: true
