apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: mistral-c7g-np
spec:
  disruption:
    budgets:
    - nodes: 10%
    consolidationPolicy: WhenUnderutilized
    expireAfter: 720h
  limits:
    cpu: 1000
  template:
    spec:
      nodeClassRef:
        name: mistral-c7g-np
      requirements:
      - key: kubernetes.io/arch
        operator: In
        values: ["arm64"]
      - key: karpenter.k8s.aws/instance-family
        operator: In
        values: ["c7g"]
      - key: karpenter.sh/capacity-type
        operator: In
        values: ["on-demand"]
      - key: karpenter.k8s.aws/instance-size
        operator: In
        values: ["4xlarge"]
---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: mistral-c7g-np
spec:
  amiFamily: AL2 
  role: $KarpenterNodeRole
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: $KarpenterDiscoveryTag
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: $KarpenterDiscoveryTag
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 300Gi
        volumeType: gp3
        encrypted: true

